environment_description:
  description: >
    Describe what is in the scene considering only {scene} and what the user is doing with the target object: {scene[main character][target]}.  
    Consider also if there are other people in the scene related to the target object.
  expected_output: >
     A single sentence describing the scene.
  agent: observer

moral_advice:
  description: >
    Create a moral advice based on your knowledge and on the context description. 
  expected_output: >
    A moral action and the related moral norm.
  agent: moralist
