environment_description:
  description: >
    Create a scene description based only on {scene} 
  expected_output: >
    Describe the scene considering only {scene}.
    Wrtite what the user is doing with a target object: {scene[user][target]}.  
    Write whether there are other people in the scene. 
  agent: observer
  tool: file_read_tool
